-- Epoch on Omarchy (Hyprland Lua config). Generated by Epoch's install.sh;
-- loaded from ~/.config/hypr/hyprland.lua with require("hypr.epoch").

-- The design is flat and solid, so opt out of Omarchy's default transparency.
o.window({ class = "^epoch$" }, { tag = "-default-opacity", opacity = "1.0 1.0" })

o.bind("SUPER + E", "Epoch", "@EPOCH_BIN@ toggle")
o.bind("SUPER + ALT + E", "Pin Epoch", "@EPOCH_BIN@ pin")

-- Keep Epoch running in the background so alarms ring with the window closed.
o.launch_on_start("@EPOCH_BIN@ daemon")
